create table if not exists public.egov_sso_profiles (
  id uuid primary key default gen_random_uuid(),
  sso_uid text not null unique,
  email text not null,
  first_name text,
  middle_name text,
  last_name text,
  suffix text,
  gender text,
  birth_date date,
  nationality text,
  mobile text,
  photo_url text,
  address text,
  street text,
  barangay text,
  barangay_code text,
  municipality text,
  municipality_code text,
  province text,
  province_code text,
  region text,
  region_code text,
  country text,
  postal text,
  tin_id text,
  passport jsonb,
  national_id jsonb,
  additional_information jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.egov_sso_profiles enable row level security;
